# Override containers for local / dev environment
version: '2.4'
services:
  reverse_proxy:
    volumes:
      - agora_nginx_data:/data

  ui:
    ports:
      - '3000:3000'
    stdin_open: true
    build:
      context: ui
      dockerfile: Dockerfile.dev
    env_file: ./ui/.env
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    ports:
      - '3001:3001'
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - agora_server_data:/data
    environment:
      - agora_ENV=local

  mongodb:
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - agora_mongodb_data:/data

volumes:
  agora_mongodb_data:
    driver: local
    name: agora_mongodb_data
  agora_server_data:
    driver: local
    name: agora_server_data
  agora_nginx_data:
    driver: local
    name: agore_nginx_data
